name: web page deploy

on:
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
          - name: checkout code
            uses: actions/checkout@v2
            
          - name: install package
            run: |
              yarn install
          - name: build
            run: |
              yarn build
        #   - name: upload dist to gh-pages
        #     uses: actions/upload-pages-artifact@v1
        #     with:
        #       path: /tmp
          - name: Push gh-pages branch
            uses: peaceiris/actions-gh-pages@v3
            with:
              # Deploy keysやPersonal access Tokensも使用可能
              github_token: ${{ secrets.ACTION_TOKEN }}
              publish_dir: ./dist