name: web page deploy

on:
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  web-page-deploy:
      runs-on: ubuntu-latest
      steps:
          - name: checkout code
            uses: actions/checkout@v2
            
          - name: install package
            run: |
              yarn install
          - name: build
            run: |
              yarn build
          - name: upload dist to gh-pages
            uses: peaceiris/actions-gh-pages@v3
            with:
              deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
              publish_dir: ./dist
